# Generated by Django 3.2.8 on 2021-11-01 09:08

from django.db import migrations, models
import keycloaklogin.usermanager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('roles', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', keycloaklogin.usermanager.KeycloakUserManager()),
            ],
        ),
    ]
